[package]
name = "njs-rust"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
env_logger = "0.9.3"
log = "0.4.17"
serde = "1.0.152"
